# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(532, 550)
        LoginWindow.setMinimumSize(QtCore.QSize(532, 550))
        LoginWindow.setMaximumSize(QtCore.QSize(532, 550))
        LoginWindow.setSizeIncrement(QtCore.QSize(0, 0))
        LoginWindow.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, -40, 551, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.tab_1)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 180, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"font-weight: normal;\n"
"outline: none;\n"
"\n"
"    \n"
"    \n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 90, 156);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.tab_1)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 240, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: normal;\n"
"outline: none;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 90, 156);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(parent=self.tab_1)
        self.label.setGeometry(QtCore.QRect(160, 90, 181, 51))
        self.label.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;\n"
"font-size: 30px")
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.tab_1)
        self.pushButton_12.setGeometry(QtCore.QRect(170, 390, 201, 41))
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"    color: rgb(47, 31, 41);\n"
"    font-size: 20px;\n"
"    border: none; /* убирает видимые границы */\n"
"    border-radius: 15px; /* делает углы кнопки закругленными */\n"
"outline: none;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_3 = QtWidgets.QLabel(parent=self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(380, 440, 58, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.tab_1)
        self.label_2.setGeometry(QtCore.QRect(240, 440, 58, 41))
        self.label_2.setStyleSheet("color: rgb(128, 128, 128);")
        self.label_2.setObjectName("label_2")
        self.label_22 = QtWidgets.QLabel(parent=self.tab_1)
        self.label_22.setGeometry(QtCore.QRect(20, 20, 81, 41))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("../icons/Снимок экрана 2025-04-10 в 12.29.49.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.tab_1)
        self.label_23.setGeometry(QtCore.QRect(240, 450, 31, 31))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("../icons/Снимок экрана 2025-04-10 в 13.48.10.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.tab_1)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 300, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"font-weight: normal;\n"
"outline: none;\n"
"\n"
"    \n"
"    \n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 90, 156);\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label.raise_()
        self.pushButton_12.raise_()
        self.label_3.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.pushButton_5.raise_()
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButton_9.setGeometry(QtCore.QRect(280, 460, 111, 41))
        self.pushButton_9.setStyleSheet("\n"
"QPushButton {\n"
"    color: black;\n"
"    border: 1px solid rgb(191, 191, 191);\n"
"    background-color: white;\n"
"    border-radius:7px\n"
"    \n"
"\n"
"    \n"
"    \n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButton_10.setGeometry(QtCore.QRect(400, 460, 111, 41))
        self.pushButton_10.setStyleSheet("\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius:7px\n"
"\n"
"\n"
"    \n"
"    \n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 460, 171, 41))
        self.pushButton_11.setStyleSheet("\n"
"QPushButton {\n"
"    color: black;\n"
"    border: 1px solid rgb(191, 191, 191);\n"
"    background-color: white;\n"
"    border-radius:7px\n"
"    \n"
"\n"
"    \n"
"    \n"
"}\n"
"P")
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_15 = QtWidgets.QLineEdit(parent=self.tab_4)
        self.lineEdit_15.setGeometry(QtCore.QRect(20, 100, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_15.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_15.setText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(parent=self.tab_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(20, 160, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_16.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_16.setText("")
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.frame_3 = QtWidgets.QFrame(parent=self.tab_4)
        self.frame_3.setGeometry(QtCore.QRect(-10, 400, 561, 20))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 101, 51))
        self.label_4.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;\n"
"font-size: 23px")
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.frame_4 = QtWidgets.QFrame(parent=self.tab_4)
        self.frame_4.setGeometry(QtCore.QRect(-20, 60, 561, 20))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.label_10 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(20, 340, 481, 41))
        self.label_10.setStyleSheet("QLabel {\n"
"    color: rgb(154, 70, 74);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(234, 214, 214); /* Границы серого цвета */\n"
"    background-color: rgb(239, 223, 222);\n"
"}\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(20, 340, 481, 41))
        self.label_11.setStyleSheet("QLabel {\n"
"    color: rgb(34, 139, 34); /* Зелёный цвет текста */\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(137,172,70); /* Границы */\n"
"    background-color: rgb(211,230,113);\n"
"}\n"
"")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(20, 160, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_9.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(20, 300, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_10.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_13 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(20, 90, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_13.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(20, 230, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_14.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(410, 460, 111, 41))
        self.pushButton_6.setStyleSheet("\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius:7px\n"
"\n"
"\n"
"    \n"
"    \n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(280, 460, 111, 41))
        self.pushButton_8.setStyleSheet("\n"
"QPushButton {\n"
"    color: black;\n"
"    border: 1px solid rgb(191, 191, 191);\n"
"    background-color: white;\n"
"    border-radius:7px\n"
"    \n"
"\n"
"    \n"
"    \n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.frame = QtWidgets.QFrame(parent=self.tab_2)
        self.frame.setGeometry(QtCore.QRect(0, 430, 561, 20))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 171, 51))
        self.label_5.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;\n"
"font-size: 23px")
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.frame_2 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(-10, 60, 561, 20))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.label_12 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_12.setEnabled(True)
        self.label_12.setGeometry(QtCore.QRect(340, 90, 191, 41))
        self.label_12.setStyleSheet("QLabel {\n"
"    color: rgb(154, 70, 74);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(234, 214, 214); /* Границы серого цвета */\n"
"    background-color: rgb(239, 223, 222);\n"
"}\n"
"")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_13.setEnabled(True)
        self.label_13.setGeometry(QtCore.QRect(340, 230, 191, 41))
        self.label_13.setStyleSheet("QLabel {\n"
"    color: rgb(154, 70, 74);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(234, 214, 214); /* Границы серого цвета */\n"
"    background-color: rgb(239, 223, 222);\n"
"}\n"
"")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(340, 160, 191, 41))
        self.label_14.setStyleSheet("QLabel {\n"
"    color: rgb(154, 70, 74);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(234, 214, 214); /* Границы серого цвета */\n"
"    background-color: rgb(239, 223, 222);\n"
"}\n"
"")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(340, 300, 191, 41))
        self.label_15.setStyleSheet("QLabel {\n"
"    color: rgb(154, 70, 74);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(234, 214, 214); /* Границы серого цвета */\n"
"    background-color: rgb(239, 223, 222);\n"
"}\n"
"")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_18 = QtWidgets.QLabel(parent=self.tab)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 371, 51))
        self.label_18.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;\n"
"font-size: 23px")
        self.label_18.setOpenExternalLinks(False)
        self.label_18.setObjectName("label_18")
        self.frame_9 = QtWidgets.QFrame(parent=self.tab)
        self.frame_9.setGeometry(QtCore.QRect(0, 70, 561, 20))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_9.setLineWidth(1)
        self.frame_9.setObjectName("frame_9")
        self.frame_10 = QtWidgets.QFrame(parent=self.tab)
        self.frame_10.setGeometry(QtCore.QRect(10, 430, 561, 20))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_10.setLineWidth(1)
        self.frame_10.setObjectName("frame_10")
        self.lineEdit_17 = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit_17.setGeometry(QtCore.QRect(20, 110, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_17.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_19 = QtWidgets.QLabel(parent=self.tab)
        self.label_19.setGeometry(QtCore.QRect(30, 350, 481, 41))
        self.label_19.setStyleSheet("QLabel {\n"
"    color: rgb(34, 139, 34); /* Зелёный цвет текста */\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(137,172,70); /* Границы */\n"
"    background-color: rgb(211,230,113);\n"
"}\n"
"")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_17.setGeometry(QtCore.QRect(270, 470, 121, 41))
        self.pushButton_17.setStyleSheet("\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: rgb(56, 82 , 151);\n"
"    border-radius:7px\n"
"\n"
"\n"
"    \n"
"    \n"
"}\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_18.setGeometry(QtCore.QRect(150, 470, 111, 41))
        self.pushButton_18.setStyleSheet("\n"
"QPushButton {\n"
"    color: black;\n"
"    border: 1px solid rgb(191, 191, 191);\n"
"    background-color: white;\n"
"    border-radius:7px\n"
"    \n"
"\n"
"    \n"
"    \n"
"}\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_20 = QtWidgets.QLabel(parent=self.tab)
        self.label_20.setGeometry(QtCore.QRect(30, 350, 481, 41))
        self.label_20.setStyleSheet("QLabel {\n"
"    color: rgb(154, 70, 74);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(234, 214, 214); /* Границы серого цвета */\n"
"    background-color: rgb(239, 223, 222);\n"
"}\n"
"")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.lineEdit_18 = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit_18.setGeometry(QtCore.QRect(20, 170, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_18.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.pushButton_32 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_32.setGeometry(QtCore.QRect(400, 470, 121, 41))
        self.pushButton_32.setStyleSheet("\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: rgb(56, 82 , 151);\n"
"    border-radius:7px\n"
"\n"
"\n"
"    \n"
"    \n"
"}\n"
"")
        self.pushButton_32.setObjectName("pushButton_32")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_29 = QtWidgets.QLineEdit(parent=self.tab_3)
        self.lineEdit_29.setGeometry(QtCore.QRect(20, 170, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_29.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_29.setText("")
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(parent=self.tab_3)
        self.lineEdit_30.setGeometry(QtCore.QRect(20, 110, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_30.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_30.setText("")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.label_41 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_41.setGeometry(QtCore.QRect(20, 10, 181, 51))
        self.label_41.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"font-weight: bold;\n"
"font-size: 23px")
        self.label_41.setOpenExternalLinks(False)
        self.label_41.setObjectName("label_41")
        self.frame_21 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame_21.setGeometry(QtCore.QRect(10, 60, 561, 20))
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_21.setLineWidth(1)
        self.frame_21.setObjectName("frame_21")
        self.frame_22 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame_22.setGeometry(QtCore.QRect(0, 420, 561, 20))
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_22.setLineWidth(1)
        self.frame_22.setObjectName("frame_22")
        self.pushButton_31 = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButton_31.setGeometry(QtCore.QRect(400, 460, 121, 41))
        self.pushButton_31.setStyleSheet("\n"
"QPushButton {\n"
"    color: white;\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius:7px\n"
"\n"
"\n"
"    \n"
"    \n"
"}\n"
"")
        self.pushButton_31.setObjectName("pushButton_31")
        self.label_21 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(30, 350, 481, 41))
        self.label_21.setStyleSheet("QLabel {\n"
"    color: rgb(154, 70, 74);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(234, 214, 214); /* Границы серого цвета */\n"
"    background-color: rgb(239, 223, 222);\n"
"}\n"
"")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.tabWidget.addTab(self.tab_3, "")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 21))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("LoginWindow", "Log in"))
        self.pushButton_4.setText(_translate("LoginWindow", "Create account"))
        self.label.setText(_translate("LoginWindow", "         Start"))
        self.pushButton_12.setText(_translate("LoginWindow", "Try first"))
        self.label_3.setText(_translate("LoginWindow", "TextLabel"))
        self.label_2.setText(_translate("LoginWindow", "          |"))
        self.pushButton_5.setText(_translate("LoginWindow", "Log out"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("LoginWindow", "Страница"))
        self.pushButton_9.setText(_translate("LoginWindow", "Cancel"))
        self.pushButton_10.setText(_translate("LoginWindow", "Login"))
        self.pushButton_11.setText(_translate("LoginWindow", "Forgot Password "))
        self.lineEdit_15.setPlaceholderText(_translate("LoginWindow", "username"))
        self.lineEdit_16.setPlaceholderText(_translate("LoginWindow", "password"))
        self.label_4.setText(_translate("LoginWindow", "Login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("LoginWindow", "Tab 1"))
        self.lineEdit_9.setPlaceholderText(_translate("LoginWindow", "email"))
        self.lineEdit_10.setPlaceholderText(_translate("LoginWindow", "phone number"))
        self.lineEdit_13.setPlaceholderText(_translate("LoginWindow", "username"))
        self.lineEdit_14.setPlaceholderText(_translate("LoginWindow", "password"))
        self.pushButton_6.setText(_translate("LoginWindow", "Sign up"))
        self.pushButton_8.setText(_translate("LoginWindow", "Cancel"))
        self.label_5.setText(_translate("LoginWindow", "Create account"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("LoginWindow", "Tab 2"))
        self.label_18.setText(_translate("LoginWindow", "Write your email for reset the code"))
        self.lineEdit_17.setPlaceholderText(_translate("LoginWindow", "email"))
        self.pushButton_17.setText(_translate("LoginWindow", "Send code"))
        self.pushButton_18.setText(_translate("LoginWindow", "Cancel"))
        self.lineEdit_18.setPlaceholderText(_translate("LoginWindow", "code"))
        self.pushButton_32.setText(_translate("LoginWindow", "Check code"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("LoginWindow", "Страница"))
        self.lineEdit_29.setPlaceholderText(_translate("LoginWindow", "confirm password"))
        self.lineEdit_30.setPlaceholderText(_translate("LoginWindow", "password"))
        self.label_41.setText(_translate("LoginWindow", "Reset password"))
        self.pushButton_31.setText(_translate("LoginWindow", "Change"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("LoginWindow", "Страница"))
