# Form implementation generated from reading ui file 'vote.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VoteWindow(object):
    def setupUi(self, VoteWindow):
        VoteWindow.setObjectName("VoteWindow")
        VoteWindow.resize(915, 367)
        VoteWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=VoteWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setStyleSheet("color: rgb(0, 0, 0);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(180, 60))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(60, 180))
        self.pushButton.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"    background-color: rgb(56, 82 , 151);\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 85, 157);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        VoteWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=VoteWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 21))
        self.menubar.setObjectName("menubar")
        VoteWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=VoteWindow)
        self.statusbar.setObjectName("statusbar")
        VoteWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VoteWindow)
        QtCore.QMetaObject.connectSlotsByName(VoteWindow)

    def retranslateUi(self, VoteWindow):
        _translate = QtCore.QCoreApplication.translate
        VoteWindow.setWindowTitle(_translate("VoteWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("VoteWindow", "choose id"))
        self.pushButton.setText(_translate("VoteWindow", "vote"))
