# Form implementation generated from reading ui file 'voting.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1470, 829)
        MainWindow.setMinimumSize(QtCore.QSize(1470, 829))
        MainWindow.setMaximumSize(QtCore.QSize(1470, 829))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -60, 1481, 191))
        self.label.setStyleSheet("background-color: rgb(63, 55, 104);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1230, 40, 191, 51))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius: 10px;\n"
"    font-size: 23px;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 40, 151, 51))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius: 10px;\n"
"    font-size: 23px;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 40, 151, 51))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: rgb(63, 55, 104);\n"
"    border-radius: 10px;\n"
"    font-size: 23px;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 110, 1471, 691))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 50, 1311, 71))
        self.label_3.setStyleSheet("QLabel {\n"
"    font-family: \"Georgia\"; /* Или \"Times New Roman\" для похожего стиля */\n"
"    font-size: 50px;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}\n"
"")
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.tab)
        self.label_4.setGeometry(QtCore.QRect(310, 160, 801, 41))
        self.label_4.setStyleSheet("QLabel {\n"
"    font-family: \"Georgia\"; /* Или \"Times New Roman\" для похожего стиля */\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(580, 410, 251, 91))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius: 10px;\n"
"    font-size: 23px;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(470, 150, 461, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_11.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_5 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(410, 30, 601, 61))
        self.label_5.setStyleSheet("QLabel {\n"
"    font-family: \"Georgia\"; /* Или \"Times New Roman\" для похожего стиля */\n"
"    font-size: 50px;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}\n"
"")
        self.label_5.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(260, 270, 221, 41))
        self.label_6.setStyleSheet("QLabel {\n"
"    font-family: \"Georgia\"; /* Или \"Times New Roman\" для похожего стиля */\n"
"    font-size: 50px;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}\n"
"")
        self.label_6.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(900, 270, 221, 41))
        self.label_7.setStyleSheet("QLabel {\n"
"    font-family: \"Georgia\"; /* Или \"Times New Roman\" для похожего стиля */\n"
"    font-size: 50px;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}\n"
"")
        self.label_7.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(610, 500, 251, 91))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius: 10px;\n"
"    font-size: 23px;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(150, 350, 461, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_12.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(910, 330, 461, 71))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_13.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(310, 80, 851, 451))
        self.tableWidget.setStyleSheet("border: 2px solid rgb(0, 0, 0); ")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_8 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(430, 10, 601, 61))
        self.label_8.setStyleSheet("QLabel {\n"
"    font-family: \"Georgia\"; /* Или \"Times New Roman\" для похожего стиля */\n"
"    font-size: 50px;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}\n"
"")
        self.label_8.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.lineEdit_14 = QtWidgets.QLineEdit(parent=self.tab_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(470, 570, 510, 61))
        self.lineEdit_14.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(510, 570))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_14.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(0, 0, 0); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(1000, 570, 161, 61))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius: 10px;\n"
"    font-size: 23px;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_9 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(60, 40, 1401, 71))
        self.label_9.setStyleSheet("QLabel {\n"
"    font-family: \"Georgia\"; /* Или \"Times New Roman\" для похожего стиля */\n"
"    font-size: 50px;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}\n"
"")
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_15 = QtWidgets.QLineEdit(parent=self.tab_4)
        self.lineEdit_15.setGeometry(QtCore.QRect(70, 180, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_15.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_15.setText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(parent=self.tab_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(70, 280, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_16.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_18 = QtWidgets.QLineEdit(parent=self.tab_4)
        self.lineEdit_18.setGeometry(QtCore.QRect(70, 380, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEdit_18.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 14px;\n"
"    border-radius: 10px;\n"
"    padding-left: 15px;\n"
"    border: 2px solid rgb(191, 191, 191); /* Границы серого цвета */\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButton_8.setGeometry(QtCore.QRect(610, 380, 161, 51))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius: 10px;\n"
"    font-size: 23px;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButton_9.setGeometry(QtCore.QRect(600, 530, 201, 71))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(63, 55, 104);\n"
"    border-radius: 10px;\n"
"    font-size: 23px;\n"
"    border: 1px solid white;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1470, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Log in"))
        self.pushButton_3.setText(_translate("MainWindow", "Vote"))
        self.pushButton_4.setText(_translate("MainWindow", "Home"))
        self.label_3.setText(_translate("MainWindow", "Welcome to  Votinng system!"))
        self.label_4.setText(_translate("MainWindow", "Create your own elections with your own candidates"))
        self.pushButton_5.setText(_translate("MainWindow", "Create"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "name of election"))
        self.label_5.setText(_translate("MainWindow", "Fill  to create elections"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Start date</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">End date</span></p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "Create"))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "(yyyy-MM-dd, HH:mm:ss)"))
        self.lineEdit_13.setPlaceholderText(_translate("MainWindow", "(yyyy-MM-dd, HH:mm:ss)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label_8.setText(_translate("MainWindow", "Welcome to elections!"))
        self.lineEdit_14.setPlaceholderText(_translate("MainWindow", "Write the name of the election you want to participate "))
        self.pushButton_7.setText(_translate("MainWindow", "Participate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Страница"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">Please, add at least 2 candidates (name , party, profile)</span></p></body></html>"))
        self.lineEdit_15.setPlaceholderText(_translate("MainWindow", "name of candidates"))
        self.lineEdit_16.setPlaceholderText(_translate("MainWindow", "party"))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "profile"))
        self.pushButton_8.setText(_translate("MainWindow", "Add"))
        self.pushButton_9.setText(_translate("MainWindow", "Finish "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Страница"))
